<?php

$p = $this->producto;

?>

<input type="hidden" id="produto" value="<?php echo $p['ID_ID_PROD']; ?>" />
<input type="hidden" id="url" value="<?php echo $this->baseUrl('/produto/index?id='.$p['ID_ID_PROD']); ?>" />
<input type="hidden" id="urlCarrinho" value="<?php echo $this->baseUrl('/carrinho/index'); ?>" />

<div class="container main-container">
        <div class="row">
       	<div class="col-lg-3 col-md-3 col-sm-12">

	<!-- 			 Best Seller 
				<div class="col-lg-12 col-md-12 col-sm-12 visible-lg visible-md">
					<div class="no-padding">
	            		<span class="title">BEST SELLER</span>
	            	</div>
		                <div class="thumbnail col-lg-12 col-md-12 col-sm-6 text-center">
		                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="<?php echo $this->baseUrl("assets/images/product-8.jpg"); ?>" alt="" style="position: absolute; width: 250px; height: auto; max-width: none; max-height: none; left: -13px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
		                        <h4><a href="detail.html">Penn State College T-Shirt</a></h4>
		                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
		                        <p>
		                        	</p><div class="btn-group">
			                        	<a href="#" class="btn btn-default">$ 528.96</a>
			                        	<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
		                <div class="thumbnail col-lg-12 col-md-12 col-sm-6 hidden-xs text-center">
		                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="<?php echo $this->baseUrl("assets/images/product-9.jpg"); ?>" alt="" style="position: absolute; width: 280px; height: auto; max-width: none; max-height: none; left: -28px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
		                        <h4><a href="detail.html">Ohio State College T-Shirt</a></h4>
		                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
		                        <p>
		                        	</p><div class="btn-group">
			                        	<a href="#" class="btn btn-default">$ 924.25</a>
			                        	<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
				</div>
				 End Best Seller -->

        	</div>

        	<div class="clearfix visible-sm"></div>

			<!-- Product Detail -->
        	<div class="col-lg-9 col-md-9 col-sm-12">
        		<div class="col-lg-12 col-sm-12">
                        <span class="title" id="titulo"><?php echo $p['ST_NOME_PROD']; ?></span>
            	</div>
	            <div class="col-lg-12 col-sm-12 hero-feature">

	            	<div class="row">
						<div class="col-lg-6 col-md-6 col-sm-6">
			            	<!-- Main Image -->
							<div class="product-main-image-container">
								<img src="<?php echo $this->baseUrl("assets/images/loader.gif"); ?>" alt="" class="product-loader" style="display: none;">
								<span class="thumbnail product-main-image" style="position: relative; overflow: hidden;">
									<img src="<?php echo $this->baseUrl("assets/images/cam".$p['ID_ID_PROD']."frente.jpg"); ?>" alt="">
								<img src="images/detail1.jpg" class="zoomImg" style="position: absolute; top: -0.33502538071066px; left: -0.0609137055837564px; opacity: 0; border: none; max-width: none; max-height: none; width: 400px; height: 400px;"></span>
							</div>
							<!-- End Main Image -->

							<!-- Thumbnail Image -->
							<div class="col-xs-3 product-thumb-image">
								<a href="<?php echo $this->baseUrl("assets/images/cam".$p['ID_ID_PROD']."frente.jpg"); ?>" class="thumbnail">
									<img src="<?php echo $this->baseUrl("assets/images/cam".$p['ID_ID_PROD']."frente.jpg"); ?>" alt="">
								</a>
							</div>
							<div class="col-xs-3 product-thumb-image">
								<a href="<?php echo $this->baseUrl("assets/images/cam".$p['ID_ID_PROD']."frentedisenho.jpg"); ?> "class="thumbnail">
									<img src="<?php echo $this->baseUrl("assets/images/cam".$p['ID_ID_PROD']."frentedisenho.jpg"); ?>" alt="">
								</a>
							</div>
							<div class="col-xs-3 product-thumb-image">
								<a href="<?php echo $this->baseUrl("assets/images/cam".$p['ID_ID_PROD']."espalda.jpg"); ?>" class="thumbnail">
									<img src="<?php echo $this->baseUrl("assets/images/cam".$p['ID_ID_PROD']."espalda.jpg"); ?>" alt="">
								</a>
							</div>
							<div class="col-xs-3 product-thumb-image">
								<a href="<?php echo $this->baseUrl("assets/images/cam".$p['ID_ID_PROD']."espaldadisenho.jpg"); ?>" class="thumbnail">
									<img src="<?php echo $this->baseUrl("assets/images/cam".$p['ID_ID_PROD']."espaldadisenho.jpg"); ?>" alt="">
								</a>
							</div>
							<!-- End Thumbnail Image -->
						</div>

						<div class="visible-xs">
							<div class="clearfix"></div>
						</div>

						<div class="col-lg-6 col-md-6 col-sm-6">
							<div class="well product-short-detail">
								<div class="row">
									<div class="the-list">
										<h3 class="col-xs-12">
                                                                                    R$
                                                                                    <span class="price-old" id="preco">
											<?php echo $p['VL_PRECO_PROD'].",00"; ?>
                                                                                    </span>
										</h3>
									</div>
									<div class="the-list">
										<div class="col-xs-4">Disponivel</div>
										<div class="col-xs-8">
											<!-- <span class="red">OUT OF STOCK</span> -->
                                                                                        <span class="green"><?php echo $p['NM_STOCK_PROD']; ?> em stock</span>
										</div>
									</div>
									<div class="the-list">
										<div class="col-xs-4">Tamanho</div>
										<div class="col-xs-8">
											<select id="tamanho" class="form-control">
												<option value="">Selecionar</option>
												<option value="P">P</option>
												<option value="M">M</option>
												<option value="G">G</option>
                                                                                                <option value="GG">GG</option>
											</select>
										</div>
									</div>
									<div class="the-list">
										<div class="col-xs-4">Frete e prazo</div>
										<div class="col-xs-8">
											<label>
												<input class="form-control" id="CEP" name="CEP" type="text" placeholder="CEP" size="8">
											</label>&nbsp;
											<label>
												<a href="javascript:void(0);" id="correio" class="btn btn-default">Calcular</a>
											</label>
										</div>
									</div>
									<div class="the-list">
										<div class="col-xs-4">Preco frete</div>
										<div class="col-xs-8">
                                                                                    <label>
                                                                                        <div id="precofrete">Nao calculado</div>
                                                                                    </label>
										</div>
									</div>
									<div class="the-list">
										<div class="col-xs-4">Dias</div>
										<div class="col-xs-8">
                                                                                    <label>
                                                                                        <div id="diasfrete">Nao calculado</div>
                                                                                    </label>
										</div>
									</div>                                                                    
									<div class="clearfix"></div>
									<hr>
									<div style="text-align:center" class="col-xs-12 input-qty-detail">
                                                                             <!-- INICIO FORMULARIO BOTAO PAGSEGURO -->
                                                                            <?php echo $p['ST_BOTAO_PROD']; ?>
<!--										<div class="input-group bootstrap-touchspin"><span class="input-group-btn"><button class="btn btn-default bootstrap-touchspin-down" id="bajar" type="button">-</button></span><span class="input-group-addon bootstrap-touchspin-prefix" style="display: none;"></span><input type="text" id="quantidade" class="form-control input-qty text-center" value="1" style="display: block;"><span class="input-group-addon bootstrap-touchspin-postfix" style="display: none;"></span><span class="input-group-btn"><button id="subir" class="btn btn-default bootstrap-touchspin-up" type="button">+</button></span></div>
										<button id="btnAdicionar" class="btn btn-default pull-left"><i class="fa fa-shopping-cart"></i> Adicionar ao carrinho</button>
                                                                                -->
									</div>
                                                                        <div style="display:none;" id="carrinhoExito" class="col-xs-12 input-qty-detail"><font color="green">Produto adicionado com exito no carrinho!!</font></div>
									<div class="clearfix"></div><br>
<!--									<div class="col-xs-12 add-to-detail">
										<div class="row">
										<div class="col-xs-6 text-center">
											<a href="compare.html"><i class="fa fa-list"></i> Add to Compare</a>
										</div>
										<div class="col-xs-6 text-center">
											<a href="wishlist.html"><i class="fa fa-heart"></i> Add to Wishlist</a>
										</div>
										</div>
									</div>-->
								</div>
							</div>
						</div>

						<div class="clearfix"></div><br clear="all">

						<div class="col-xs-12 product-detail-tab">
							<!-- Nav tabs -->
							<ul class="nav nav-tabs">
								<li class="active"><a href="#desc" data-toggle="tab">Descrição</a></li>
								<li><a href="#detail" data-toggle="tab">Historia</a></li>
                                
<!--								<li><a href="#review" data-toggle="tab">Opin</a></li>-->
							</ul>

							<!-- Tab panes -->
							<div class="tab-content">
								<div class="tab-pane active" id="desc">
									<div class="well">
										<p><?php echo $p['ST_DESCRICAO_PROD']; ?></p>
									</div>
								</div>
								<div class="tab-pane" id="detail">
									<div class="well">
										<?php echo $p['ST_HISTORIA_PROD']; ?>
									</div>
								</div>
								<div class="tab-pane" id="review">
									<div class="well">
										<div class="media">
											<a class="pull-left" href="#">
												<img class="media-object" alt="64x64" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCI+PHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiBmaWxsPSIjZWVlIi8+PHRleHQgdGV4dC1hbmNob3I9Im1pZGRsZSIgeD0iMzIiIHk9IjMyIiBzdHlsZT0iZmlsbDojYWFhO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjEycHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9zdmc+">
												<div class="product-rating">
													<i class="fa fa-star"></i>
													<i class="fa fa-star"></i>
													<i class="fa fa-star"></i>
													<i class="fa fa-star"></i>
													<i class="fa fa-star-half-o"></i>
												</div>
											</a>
											<div class="media-body">
												<h5 class="media-heading"><strong>John Thor</strong></h5>
												Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
											</div>
										</div>
										<div class="media">
											<a class="pull-left" href="#">
												<img class="media-object" alt="64x64" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCI+PHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiBmaWxsPSIjZWVlIi8+PHRleHQgdGV4dC1hbmNob3I9Im1pZGRsZSIgeD0iMzIiIHk9IjMyIiBzdHlsZT0iZmlsbDojYWFhO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjEycHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9zdmc+">
												<div class="product-rating">
													<i class="fa fa-star"></i>
													<i class="fa fa-star"></i>
													<i class="fa fa-star"></i>
													<i class="fa fa-star-half-o"></i>
													<i class="fa fa-star-o"></i>
												</div>
											</a>
											<div class="media-body">
												<h5 class="media-heading"><strong>Michael</strong></h5>
												Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
											</div>
										</div>
										<hr>
		                                <h4>Add your review</h4>
		                                <p></p>
		                                <form role="form">
		                                    <div class="form-group">
		                                        <input type="text" class="form-control" placeholder="Name">
		                                    </div>
		                                    <div class="form-group">
		                                        <input type="text" class="form-control" placeholder="Email">
		                                    </div>
		                                    <div class="form-group">
		                                        <select class="form-control">
		                                            <option>1 star</option>
		                                            <option>2 stars</option>
		                                            <option>3 stars</option>
		                                            <option>4 stars</option>
		                                            <option>5 stars</option>
		                                        </select>
		                                    </div>
		                                    <div class="form-group">
		                                        <textarea class="form-control" rows="5" placeholder="Your Review"></textarea>
		                                    </div>
		                                    <button type="submit" class="btn btn-default">Submit Review</button>
		                                </form>
									</div>
								</div>
							</div>
						</div>
					</div>

					<!-- <div class="addthis_toolbox addthis_default_style addthis_32x32_style">
						<a class="addthis_button_preferred_1"></a>
						<a class="addthis_button_preferred_2"></a>
						<a class="addthis_button_preferred_3"></a>
						<a class="addthis_button_preferred_4"></a>
						<a class="addthis_button_compact"></a>
					</div>
					<script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=xa-4f0c254f1302adf8"></script>
	             -->
	            </div>
	            <div class="clearfix"></div>
	          <!--  <div class="col-lg-12 col-sm-12">
            		<span class="title">RELATED PRODUCTS</span>
            	</div>
            	<div class="col-lg-4 col-sm-4 hero-feature text-center">
	                <div class="thumbnail">
	                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
	                    	<img src="<?php echo $this->baseUrl("assets/images/product-10.jpg"); ?>" alt="" style="position: absolute; width: 242px; height: 258px; max-width: none; max-height: none; left: 0px; top: 0px;">
	                	</a>
	                    <div class="caption prod-caption">
	                        <h4><a href="detail.html">Adidas Men Blue &amp; Red Striped Polo T-shirt </a></h4>
	                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
	                        <p>
	                        	</p><div class="btn-group">
		                        	<a href="#" class="btn btn-default">$ 22.22</a>
		                        	<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
	                        	</div>
	                        <p></p>
	                    </div>
	                </div>
	            </div>
	            <div class="col-lg-4 col-sm-4 hero-feature text-center">
	                <div class="thumbnail">
	                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
	                    	<img src="<?php echo $this->baseUrl("assets/images/product-11.jpg"); ?>" alt="" style="position: absolute; width: 248px; height: auto; max-width: none; max-height: none; left: -3px; top: 0px;">
	                	</a>
	                    <div class="caption prod-caption">
	                        <h4><a href="detail.html">Adidas Men Flame Black T-shirt</a></h4>
	                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
	                        <p>
	                        	</p><div class="btn-group">
	                        		<a href="#" class="btn btn-default">$ 15.47</a>
	                        		<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
	                        	</div>
	                        <p></p>
	                    </div>
	                </div>
	            </div>
	            <div class="col-lg-4 col-sm-4 hero-feature text-center">
	                <div class="thumbnail">
	                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
	                    	<img src="<?php echo $this->baseUrl("assets/images/product-12.jpg"); ?>" alt="" style="position: absolute; width: 251px; height: auto; max-width: none; max-height: none; left: -4px; top: 0px;">
	                	</a>
	                    <div class="caption prod-caption">
	                        <h4><a href="detail.html">Adidas Men Red Printed T-shirt</a></h4>
	                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
	                        <p>
	                        	</p><div class="btn-group">
	                        		<a href="#" class="btn btn-default">$ 20.63</a>
	                        		<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
	                        	</div>
	                        <p></p>
	                    </div>
	                </div>
	            </div>
        	</div>
        	<!-- End Product Detail -->


        </div>
	</div>
    <div>
        <img src="<?php echo $this->baseUrl("assets/images/pagamentos.jpg"); ?>" alt=""/>
    </div>
    <script type="text/javascript">
        $(function() {
            $('#subir').bind('click', function() {
               var valor = Number($('#quantidade').val());
               $('#quantidade').val(valor+Number(1));
            });

            $('#bajar').bind('click', function() {
               var valor = Number($('#quantidade').val());
               if (valor > 1) {
                $('#quantidade').val(valor-Number(1));
                }
            });
            
            $('#correio').bind('click', function() {
                $.post('correio',{CEP: $('#CEP').val()}, function(response) {
                   var prazo = response.Prazo.PrazoEntrega + " dia(s)";
                   var precoAux = (parseFloat(response.Preco.Valor)  - 10).toString();
                   var preco = 'R$ ' + precoAux.slice(0,4);
                   console.log(response.Preco.Valor);
                   if (response.Prazo.MsgErro.length !== 0) {
                       prazo = '<font color="red">'+response.Prazo.MsgErro+'</font>';
                   }
                   
                   if (response.Preco.MsgErro.length !== 0) {
                       preco = '<font color="red">'+response.Preco.MsgErro+'</font>';
                   }
        
                    $('#precofrete').html(preco);
                    $('#diasfrete').html(prazo);
                    console.log(response);
                });
            });

           $('#btnAdicionar').bind('click', function() {
                var idVenta = Math.floor((Math.random() * 10000) + 1);
                $.post("adicionar", {quantidade: $('#quantidade').val(), produto: $('#produto').val(), titulo: $('#titulo').html(), tamanho: $('#tamanho').val(), preco: $('#preco').html(), idVenta: idVenta }, function(response) {
                   
                   var html = "";
                   var total = Number(0);
                   var i = Number(0);
                   $.each(response, function(key, value) {
                        var id = (response[key].id);               
                        var titulo = (response[key].titulo);
                        var tamanho = response[key].tamanho;
                        var preco = response[key].preco;
                        var quantidade = response[key].quantidade;
                        
                        html = html + '<li><a href="'+$('#url').val()+'"><b>'+titulo+'</b><span>('+quantidade+') - '+tamanho+' R$' + preco + '</span></a></li>';
                        total = total + Number(preco);
                        i += Number(quantidade);
                   });
                    var urlCarro = $('#urlCarrinho').val();
                    console.log(response);
                    var tot = '<li class="divider"></li><li><a href="'+urlCarro+'">Total: R$ '+total+'</a></li>';
                    $('#carrinho').html(html+tot); 
                    $('#tituloCarrinho').html('Carrinho: '+i+' item(s)');
                    $('#carrinhoExito').css("display","inline");
               })
           }) 
        });
    
    </script>