<?php

 $estados = $this->estados;
 
?>

<div class="container main-container">
        <div class="row">
        	<div class="col-lg-3 col-md-3 col-sm-12">

				<!-- RECENT PRODUCT -->
				<div class="col-lg-12 col-md-12 col-sm-12">
					<div class="no-padding">
	            		<span class="title">RECENT PRODUCT</span>
	            	</div>
		                <div class="thumbnail col-lg-12 col-md-12 col-sm-6 text-center">
		                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="<?php echo $this->baseUrl("assets/images/product-5.jpg"); ?>" alt="" style="position: absolute; width: 250px; height: auto; max-width: none; max-height: none; left: -13px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
		                        <h4><a href="detail.html">Live Nation 3 Days of Peace and Music Carbon</a></h4>
		                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
		                        <p>
		                        	</p><div class="btn-group">
			                        	<a href="#" class="btn btn-default">$ 428.96</a>
			                        	<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
		                <div class="thumbnail col-lg-12 col-md-12 col-sm-6 visible-sm text-center">
		                	<a href="<?php echo $this->baseUrl("/produto/index?id=1"); ?>" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="/ecomerce/public/assets/images/cam1frente.jpg" alt="" style="position: absolute; width: 224px; height: auto; max-width: none; max-height: none; left: 0px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
                                        <h4><a href="<?php echo $this->baseUrl("/produto/index?id=1"); ?>">Camiseta Born To Fight</a></h4>
		                        <p>Fachada da sede do Andre Gomes Team. Os melhores lutadores da historia do Muaythai tiraram fotos.</p>
		                        <p>
		                        	</p><div class="btn-group">
			                        	<a href="#" class="btn btn-default">R$ 69</a>
			                        	<a href="<?php echo $this->baseUrl("/produto/index?id=1"); ?>" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Comprar</a>
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
				</div>
				<!-- End RECENT PRODUCT -->

        	</div>

        	<div class="clearfix visible-sm"></div>

			<!-- Cart -->
        	<div class="col-lg-9 col-md-9 col-sm-12">
        		<div class="col-lg-12 col-sm-12">
            		<span class="title">ENCERRAR CARRINHO</span>
            	</div>
	            <div class="col-lg-12 col-sm-12 hero-feature">
					<table class="table table-bordered tbl-checkout">
						<tbody>
                            <tr>
                                <td>Nome</td>
                                <td>
                                    <input type="text" name="" class="form-control">
                                </td>
                                <td>Sobrenome</td>
                                <td>
                                    <input type="text" name="" class="form-control">
                                </td>
                            </tr>
                            <tr>
                                <td>E-mail</td>
                                <td>
                                    <input type="text" name="" class="form-control">
                                </td>
                                <td>Telefone</td>
                                <td>
                                    <input type="text" name="" class="form-control">
                                </td>
                            </tr>
                            <tr>
                                <td>Endereco</td>
                                <td colspan="3">
                                    <textarea name="" class="form-control"></textarea>
                                </td>
                            </tr>
                            <tr>
                                <td>Cidade</td>
                                <td>
                                    <select class="form-control" id="cidades">
                                        <?php
                                        
                                        ?>
                                      </select>
                                </td>
                                <td>CEP</td>
                                <td>
                                    <input type="text" name="" class="form-control">
                                </td>
                            </tr>
                            <tr>
                                <td>Pais</td>
                                <td>
                                    <select class="form-control">
                                        <option value="1"> Brasil </option>
                                      </select>
                                </td>
                                <td class="tujuan">Estado</td>
                                <td class="jne">
                                    <select class="form-control" id="estado"><option value=""> --- Selecione cidade --- </option>
                                        <?php
                                            for ($i = 0; $i < count($estados); $i++) {
                                                echo '<option value="'.$estados[$i]['id'].'">'.$estados[$i]['nome'].'</option>';
                                            }
                                        
                                        ?>
                                    </select>    
                                 </td>
                            </tr>
                            <tr>
                                <td>Comentario</td>
                                <td colspan="3">
                                    <textarea name="" class="form-control"></textarea>
                                </td>
                            </tr>
                        </tbody>
					</table>
                    <table class="table table-bordered tbl-cart">
                        <thead>
                            <tr>
                                <td>Product Name</td>
                                <td>Size</td>
                                <td>Color</td>
                                <td class="td-qty">Quantity</td>
                                <td>Unit Price</td>
                                <td>Sub Total</td>
                                <td>Action</td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Age Of Wisdom Tan Graphic Tee</td>
                                <td>M</td>
                                <td>-</td>
                                <td class="text-center">1</td>
                                <td class="price">$ 122.21</td>
                                <td>$ 122.21</td>
                                <td class="text-center">
                                    <a href="#" class="remove_cart" rel="2">
                                        <i class="fa fa-trash-o"></i>
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td>Adidas Men Red Printed T-shirt</td>
                                <td>S</td>
                                <td>Red</td>
                                <td class="text-center">2</td>
                                <td class="price">$ 20.63</td>
                                <td>$ 41.26</td>
                                <td class="text-center">
                                    <a href="#" class="remove_cart" rel="1">
                                        <i class="fa fa-trash-o"></i>
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="5" align="right">Flat Shipping Rate</td>
                                <td class="total" colspan="2"><b>$ 5.00</b></td>
                            </tr>
                            <tr>
                                <td colspan="5" align="right">Total</td>
                                <td class="total" colspan="2"><b>$ 168.47</b></td>
                            </tr>
                        </tbody>
                    </table>
					<div class="btn-group btns-cart">
						<button type="button" class="btn btn-primary">Continue</button>
					</div>

	            </div>
        	</div>
        	<!-- End Cart -->


        </div>
	</div>


<script type="text/javascript"> 
    
    $(function() {
        $('#estado').bind('click', function() {
           $.post('cidade',{estado: $('#estado').val()}, function(response) {
               console.log(response);
           }) ;
        });
    });

</script>