<?php

 $estados = $this->estados;
 
// $storage = new Zend_Auth_Storage_Session();
// print_r($storage->read());
// die('.');
 
?>

<div class="container main-container">
        <div class="row">
        	<div class="col-lg-3 col-md-3 col-sm-12">

				<!-- RECENT PRODUCT -->
				<div class="col-lg-12 col-md-12 col-sm-12">
					<div class="no-padding">
	            		<span class="title">BEST SELLER</span>
	            	</div>
		                <div class="thumbnail col-lg-12 col-md-12 col-sm-6 text-center">
		                	<a href="<?php echo $this->baseUrl("/produto/index?id=1"); ?>" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="<?php echo $this->baseUrl("assets/images/cam1frente.jpg"); ?>" alt="" style="position: absolute; width: 224px; height: auto; max-width: none; max-height: none; left: 0px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
                                        <h4><a href="<?php echo $this->baseUrl("/produto/index?id=1"); ?>">Camiseta Born To Fight</a></h4>
		                        <p>Fachada da sede do Andre Gomes Team. Os melhores lutadores da historia do Muaythai tiraram fotos.</p>
		                        <p>
		                        	</p><div class="btn-group">
			                        	<a href="#" class="btn btn-default">R$ 69</a>
			                        	<a href="<?php echo $this->baseUrl("/produto/index?id=1"); ?>" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Comprar</a>
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
		                <div class="thumbnail col-lg-12 col-md-12 col-sm-6 visible-sm text-center">
		                	<a href="<?php echo $this->baseUrl("/produto/index?id=1"); ?>" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="/ecomerce/public/assets/images/cam1frente.jpg" alt="" style="position: absolute; width: 224px; height: auto; max-width: none; max-height: none; left: 0px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
                                        <h4><a href="<?php echo $this->baseUrl("/produto/index?id=1"); ?>">Camiseta Born To Fight</a></h4>
		                        <p>Fachada da sede do Andre Gomes Team. Os melhores lutadores da historia do Muaythai tiraram fotos.</p>
		                        <p>
		                        	</p><div class="btn-group">
			                        	<a href="#" class="btn btn-default">R$ 69</a>
			                        	<a href="<?php echo $this->baseUrl("/produto/index?id=1"); ?>" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Comprar</a>
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
				</div>
				<!-- End RECENT PRODUCT -->

        	</div>

        	<div class="clearfix visible-sm"></div>

			<!-- Cart -->
        	<div class="col-lg-9 col-md-9 col-sm-12">
        		<div class="col-lg-12 col-sm-12">
            		<span class="title">ENCERRAR CARRINHO</span>
            	</div>
	            <div class="col-lg-12 col-sm-12 hero-feature">
                        <form action="<?php echo $this->baseUrl('/carrinho/encerrar'); ?>" method="post">
					<table class="table table-bordered tbl-checkout">
						<tbody>
                            <tr>
                                <td>Nome</td>
                                <td>
                                    <input type="text" name="nome" class="form-control">
                                </td>
                                <td>Sobrenome</td>
                                <td>
                                    <input type="text" name="sobrenome" class="form-control">
                                </td>
                            </tr>
                            <tr>
                                <td>E-mail</td>
                                <td>
                                    <input type="text" name="email" class="form-control">
                                </td>
                               <td>CEP</td>
                                <td>
                                    <input type="text" name="CEP" id="CEP" class="form-control">
                                </td>
                            </tr>
                            <tr>
                                <td>Endereco</td>
                                <td colspan="3">
                                    <textarea id="endereco" name="endereco" class="form-control"></textarea>
                                </td>
                            </tr>
                            <tr>
                                <td class="tujuan">Estado</td>
                                <td class="jne">
                                    <select name="estado" class="form-control" id="estado"><option value=""> --- Selecione cidade --- </option>
                                        <?php
                                            for ($i = 0; $i < count($estados); $i++) {
                                                echo '<option value="'.$estados[$i]['nome'].'">'.$estados[$i]['nome'].'</option>';
                                            }
                                        
                                        ?>
                                    </select>    
                                 </td>
                                <td>Cidade</td>
                                <td>
                                    <select name="cidade" class="form-control" id="cidades">
                                        <?php
                                        
                                        ?>
                                      </select>
                                </td>
                                
                            </tr>
                            <tr>
                                <td>Pais</td>
                                <td>
                                    <select name="pais" class="form-control">
                                        <option value="1"> Brasil </option>
                                      </select>
                                </td>
                                <td>Telefone</td>
                                <td>
                                    <input type="text" name="telefone" class="form-control">
                                </td>
                            </tr>
                            <tr>
                                <td>Comentario</td>
                                <td colspan="3">
                                    <textarea name="comentario" class="form-control"></textarea>
                                </td>
                            </tr>
                        </tbody>
					</table>
                        				                           
                            <?php
                                $storage = new Zend_Auth_Storage_Session();
                                $data = $storage->read();
                            ?>
                            
                            <?php
                                $total = 0;
                            for ($i = 0; $i < count($data); $i++) {
                                if ($total == 0) {
                                    echo '<table class="table table-bordered tbl-cart">
						<thead>
                            <tr>
                                <td class="hidden-xs">Foto</td>
                                <td>Produto</td>
                                <td>Tamanho</td>
                                <td>Color</td>
                                <td class="td-qty">Quantidade</td>
                                <td>Preco</td>
                                <td>Sub Total</td>
                                <td>Excluir</td>
                            </tr>
                        </thead>
                        <tbody>';
                                }
                                
                                $total += $data[$i]['preco'];
                                
                                echo '<tr>
                                <td class="hidden-xs">
                                    <a href="'.$this->baseUrl('/produto/index?id='.$data[$i]['id']).'">
                                        <img src="'.$this->baseUrl("assets/images/cam".$data[$i]['id']."frente.jpg").'" alt="'.$data[$i]['titulo'].'" title="" width="47" height="47">
                                    </a>
                                </td>
                                <td><a href="detail.html">'.$data[$i]['titulo'].'</a>
                                </td>
                                <td>
                                    '.$data[$i]['tamanho'].'
                                </td>
                                <td>-</td>
                                <td>
                                    <div class="input-group bootstrap-touchspin"><span class="input-group-btn"><button class="btn btn-default bootstrap-touchspin-down" type="button">-</button></span><span class="input-group-addon bootstrap-touchspin-prefix" style="display: none;"></span><input type="text" name="" value="'.$data[$i]['quantidade'].'" class="input-qty form-control text-center" style="display: block;"><span class="input-group-addon bootstrap-touchspin-postfix" style="display: none;"></span><span class="input-group-btn"><button class="btn btn-default bootstrap-touchspin-up" type="button">+</button></span></div>
                                </td>
                                <td class="price">R$ '.$data[$i]['preco'].'</td>
                                <td>R$ '.$data[$i]['preco'].'</td>
                                <td class="text-center">
                                    <a href="#" class="remove_cart" rel="2">
                                        <i class="fa fa-trash-o excluir" data-idVenta="'.$data[$i]['idVenta'].'" data-pos="'.$i.'"></i>
                                    </a>
                                </td>
                            </tr>
                            ';}
                            ?>
                            
                            <?php
                            if ($total > 0) {
                             echo '<tr>
                                <td colspan="6" align="right">Total</td>
                                <td class="total" colspan="2"><b>R$ '.$total.'</b>
                                </td>
                            </tr>';
                            } else {
                                echo 'Carrinho vazio.<br><br>';
                            }
                            
                            ?>
                        </tbody>
					</table>
					<div class="btn-group btns-cart">
						<input type="submit" class="btn btn-primary" value="Continuar" />  
					</div>
</form>
	            </div>
        	</div>
        	<!-- End Cart -->


        </div>
	</div>


<script type="text/javascript"> 
    
    $(function() {
        $('#CEP').bind('change', function() {
           console.log("mudou");
           var cep = $('#CEP').val();
           $.getJSON( "http://cep.correiocontrol.com.br/"+cep+".json", function( data ) {
               // if (data )
               $('#endereco').val(data.logradouro);
                console.log(data);
           });
        });
        
        $('#estado').bind('click', function() {
           $.post('cidade',{estado: $('#estado').val()}, function(response) {
               var cidades = "";
               $.each(response, function(key,value) {
                   cidades = cidades + '<option value="'+response[key].nome+'"> '+response[key].nome+' </option>';
                   console.log(response[key].nome);
               });
               $('#cidades').html(cidades);
//               <option value="1"> Brasil </option>
//               console.log(response);
           }) ;
        });
        
        $('.excluir').bind('click', function() {
           var idVenta = $(this).data('idventa');
           $.post('excluirproduto', {idventa:idVenta}, function(response) {
               window.location.reload();
                console.log(response);
           });
        });
    });

</script>