<?php 

 echo '<input type="hidden" value="'.$this->baseUrl('/carrinho/excluirproduto').'" id="dir" />';

?>


<div class="container main-container">
        <div class="row">
        	<div class="col-lg-3 col-md-3 col-sm-12">

				<!-- Best Seller -->
				<div class="col-lg-12 col-md-12 col-sm-12">
					<div class="no-padding">
	            		<span class="title">BEST SELLER</span>
	            	</div>
		                <div class="thumbnail col-lg-12 col-md-12 col-sm-6 text-center">
		                	<a href="<?php echo $this->baseUrl("/produto/index?id=1"); ?>" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="/ecomerce/public/assets/images/cam1frente.jpg" alt="" style="position: absolute; width: 224px; height: auto; max-width: none; max-height: none; left: 0px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
                                        <h4><a href="<?php echo $this->baseUrl("/produto/index?id=1"); ?>">Camiseta Born To Fight</a></h4>
		                        <p>Fachada da sede do Andre Gomes Team. Os melhores lutadores da historia do Muaythai tiraram fotos.</p>
		                        <p>
		                        	</p><div class="btn-group">
			                        	<a href="#" class="btn btn-default">R$ 69</a>
			                        	<a href="<?php echo $this->baseUrl("/produto/index?id=1"); ?>" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Comprar</a>
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
		                <div class="thumbnail col-lg-12 col-md-12 col-sm-6 visible-sm text-center">
		                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="<?php echo $this->baseUrl("assets/images/product-9.jpg"); ?>" alt="" style="position: absolute; width: auto; height: auto; max-width: none; max-height: none; left: 50px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
		                        <h4><a href="detail.html">Ohio State College T-Shirt</a></h4>
		                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
		                        <p>
		                        	</p><div class="btn-group">
			                        	<a href="#" class="btn btn-default">$ 924.25</a>
			                        	<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
				</div>
				<!-- End Best Seller -->

        	</div>

        	<div class="clearfix visible-sm"></div>

			<!-- Cart -->
        	<div class="col-lg-9 col-md-9 col-sm-12">
        		<div class="col-lg-12 col-sm-12">
            		<span class="title">CARRINHO</span>
            	</div>
	            <div class="col-lg-12 col-sm-12 hero-feature">
					
                            
                            <?php
                                $storage = new Zend_Auth_Storage_Session();
                                $data = $storage->read();
                            ?>
                            
                            <?php
                                $total = 0;
                            for ($i = 0; $i < count($data); $i++) {
                                
                                
                            
                                if ($total == 0) {
                                    echo '<table class="table table-bordered tbl-cart">
						<thead>
                            <tr>
                                <td class="hidden-xs">Foto</td>
                                <td>Produto</td>
                                <td>Tamanho</td>
                                <td>Color</td>
                                <td class="td-qty">Quantidade</td>
                                <td>Preco</td>
                                <td>Sub Total</td>
                                <td>Excluir</td>
                            </tr>
                        </thead>
                        <tbody>';
                                }
                                
                                $total += $data[$i]['preco'];
                                
                                echo '<tr>
                                <td class="hidden-xs">
                                    <a href="'.$this->baseUrl('/produto/index?id='.$data[$i]['id']).'">
                                        <img src="'.$this->baseUrl("assets/images/product-2.jpg").'" alt="'.$data[$i]['titulo'].'" title="" width="47" height="47">
                                    </a>
                                </td>
                                <td><a href="detail.html">'.$data[$i]['titulo'].'</a>
                                </td>
                                <td>
                                    '.$data[$i]['tamanho'].'
                                </td>
                                <td>-</td>
                                <td>
                                    <div class="input-group bootstrap-touchspin"><span class="input-group-btn"><button class="btn btn-default bootstrap-touchspin-down" type="button">-</button></span><span class="input-group-addon bootstrap-touchspin-prefix" style="display: none;"></span><input type="text" name="" value="'.$data[$i]['quantidade'].'" class="input-qty form-control text-center" style="display: block;"><span class="input-group-addon bootstrap-touchspin-postfix" style="display: none;"></span><span class="input-group-btn"><button class="btn btn-default bootstrap-touchspin-up" type="button">+</button></span></div>
                                </td>
                                <td class="price">R$ '.$data[$i]['preco'].'</td>
                                <td>R$ '.$data[$i]['preco'].'</td>
                                <td class="text-center">
                                    <a href="#" class="remove_cart" rel="2">
                                        <i class="fa fa-trash-o excluir" data-idVenta="'.$data[$i]['idVenta'].'" data-pos="'.$i.'"></i>
                                    </a>
                                </td>
                            </tr>
                            ';}
                            ?>
                            
                            <?php
                            if ($total > 0) {
                             echo '<tr>
                                <td colspan="6" align="right">Total</td>
                                <td class="total" colspan="2"><b>R$ '.$total.'</b>
                                </td>
                            </tr>';
                            } else {
                                echo 'Carrinho vazio.<br><br>';
                            }
                            
                            ?>
                        </tbody>
					</table>
					<div class="btn-group btns-cart">
						<a class="btn btn-primary" href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-arrow-circle-left"></i> Continuar Comprando</a>
						<a class="btn btn-primary" href="<?php echo $this->baseUrl("/carrinho/checkout"); ?>">Encerrar Carrinho <i class="fa fa-arrow-circle-right"></i></a>
					</div>

	            </div>
        	</div>
        	<!-- End Cart -->


        </div>
	</div>


<script type="text/javascript">
    
    $(function() {
        $('.excluir').bind('click', function() {
           var idVenta = $(this).data('idventa');
           var dir = $('#dir').val();
           $.post(dir, {idventa:idVenta}, function(response) {
               window.location.reload();
               console.log(response);
           });
        });
    });
    
    
</script>