<div class="container main-container">
        <div class="row">
        	<div class="col-lg-3 col-md-3 col-sm-12">

				<!-- Best Seller -->
				<div class="col-lg-12 col-md-12 col-sm-12">
					<div class="no-padding">
	            		<span class="title">BEST SELLER</span>
	            	</div>
		                <div class="thumbnail col-lg-12 col-md-12 col-sm-6 text-center">
		                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="<?php echo $this->baseUrl("assets/images/product-8.jpg"); ?>" alt="" style="position: absolute; width: 250px; height: auto; max-width: none; max-height: none; left: -13px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
		                        <h4><a href="detail.html">Penn State College T-Shirt</a></h4>
		                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
		                        <p>
		                        	</p><div class="btn-group">
			                        	<a href="#" class="btn btn-default">$ 528.96</a>
			                        	<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
		                <div class="thumbnail col-lg-12 col-md-12 col-sm-6 visible-sm text-center">
		                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="<?php echo $this->baseUrl("assets/images/product-9.jpg"); ?>" alt="" style="position: absolute; width: auto; height: auto; max-width: none; max-height: none; left: 50px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
		                        <h4><a href="detail.html">Ohio State College T-Shirt</a></h4>
		                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
		                        <p>
		                        	</p><div class="btn-group">
			                        	<a href="#" class="btn btn-default">$ 924.25</a>
			                        	<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
				</div>
				<!-- End Best Seller -->

        	</div>

        	<div class="clearfix visible-sm"></div>

			<!-- Cart -->
        	<div class="col-lg-9 col-md-9 col-sm-12">
        		<div class="col-lg-12 col-sm-12">
            		<span class="title">CARRINHO</span>
            	</div>
	            <div class="col-lg-12 col-sm-12 hero-feature">
					<table class="table table-bordered tbl-cart">
						<thead>
                            <tr>
                                <td class="hidden-xs">Foto</td>
                                <td>Produto</td>
                                <td>Tamanho</td>
                                <td>Color</td>
                                <td class="td-qty">Quantidade</td>
                                <td>Preco</td>
                                <td>Sub Total</td>
                                <td>Excluir</td>
                            </tr>
                        </thead>
                        <tbody>
                            
                            <?php
                                $storage = new Zend_Auth_Storage_Session();
                                $data = $storage->read();
                            ?>
                            
                            <?php
                                $total = 0;
                            for ($i = 0; $i < count($data); $i++) {
                                $total += $data[$i]['preco'];
                            echo '<tr>
                                <td class="hidden-xs">
                                    <a href="detail.html">
                                        <img src="'.$this->baseUrl("assets/images/product-2.jpg").'" alt="'.$data[$i]['titulo'].'" title="" width="47" height="47">
                                    </a>
                                </td>
                                <td><a href="detail.html">'.$data[$i]['titulo'].'</a>
                                </td>
                                <td>
                                    <select name="">
                                        <option value="" selected="selected">S</option>
                                        <option value="">M</option>
                                    </select>
                                </td>
                                <td>-</td>
                                <td>
                                    <div class="input-group bootstrap-touchspin"><span class="input-group-btn"><button class="btn btn-default bootstrap-touchspin-down" type="button">-</button></span><span class="input-group-addon bootstrap-touchspin-prefix" style="display: none;"></span><input type="text" name="" value="'.$data[$i]['quantidade'].'" class="input-qty form-control text-center" style="display: block;"><span class="input-group-addon bootstrap-touchspin-postfix" style="display: none;"></span><span class="input-group-btn"><button class="btn btn-default bootstrap-touchspin-up" type="button">+</button></span></div>
                                </td>
                                <td class="price">R$ '.$data[$i]['preco'].'</td>
                                <td>R$ '.$data[$i]['preco'].'</td>
                                <td class="text-center">
                                    <a href="#" class="remove_cart" rel="2">
                                        <i class="fa fa-trash-o excluir" data-pos="'.$i.'"></i>
                                    </a>
                                </td>
                            </tr>
                            ';}
                            ?>
                            <tr>
                                <td colspan="6" align="right">Total</td>
                                <td class="total" colspan="2"><b>R$ <?php echo $total ?></b>
                                </td>
                            </tr>
                        </tbody>
					</table>
					<div class="btn-group btns-cart">
						<button type="button" class="btn btn-primary" onclick="window.location='catalogue.html'"><i class="fa fa-arrow-circle-left"></i> Continuar Comprando</button>
						<button type="button" class="btn btn-primary">Atualizar Carrinho</button>
						<button type="button" class="btn btn-primary" onclick="window.location='checkout.html'">Encerrar Carrinho <i class="fa fa-arrow-circle-right"></i></button>
					</div>

	            </div>
        	</div>
        	<!-- End Cart -->


        </div>
	</div>


<script type="text/javascript">
    
    $(function() {
       $('.excluir').bind('click', function() {
           
       });
    });
    
    
</script>