<div class="container">

        <div class="col-lg-8 col-md-8 col-sm-8">
            <div class="white-container">
                <span class="title">CADASTRO</span>
                <p>Para poder comprar precisa se cadastrar.</p>

                <!-- Form Register -->
                <form action="<?php echo $this->baseUrl("/index/cadastrar"); ?>" method="post">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <label for="email">Email (*)</label>
                        <input type="text" name="email" class="form-control" id="email"><br clear="all">
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <label for="password">Senha (*)</label>
                        <input type="password" name="senha" class="form-control" id="password"><br clear="all">
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <label for="confirm_password">Confirmaçao (*)</label>
                        <input type="password" name="confirmacao" class="form-control" id="confirm_password"><br clear="all">
                    </div>
                    <div class="clearfix"></div>
                    <button class="btn btn-danger">Cadastrar</button>
                </form>
                <!-- End Form Register -->
            </div>

        </div>

        <div class="col-lg-4 col-md-4 col-sm-4">

            <!-- Login Form -->
            <div class="white-container">
                <span class="title">JÁ USUARIO ?</span>
                <form role="form">
                    <div class="form-group">
                        <div class="input-group login-input">
                            <span class="input-group-addon"><i class="fa fa-user"></i></span>
                            <input type="text" name="email" class="form-control" placeholder="Email">
                        </div>
                        <br>
                        <div class="input-group login-input">
                            <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                            <input type="password" name="senha" class="form-control" placeholder="Senha">
                        </div>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox"> Lembrar
                            </label>
                        </div>
                        <button type="submit" class="btn btn-sm btn-primary pull-right"><i class="fa fa-long-arrow-right"></i> Entrar</button>
                        <button type="button" class="btn btn-xs btn-primary btn-login-social"><i class="fa fa-facebook"></i></button>
                    </div>
                </form>
            </div>
            <!-- End Login Form -->

        </div>

    </div>