<div class="container main-container">
        <div class="row">
        	<div class="col-lg-3 col-md-3 col-sm-12">

				<!-- OUR LOCATION -->
				<div class="col-lg-12 col-md-12 col-sm-12">
					<div class="no-padding">
	            		<span class="title">OUR LOCATION</span>
                                <div class="fb-page" data-href="https://www.facebook.com/pages/World-Fight/387486434779917" data-width="500" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/pages/World-Fight/387486434779917"><a href="https://www.facebook.com/pages/World-Fight/387486434779917">World Fight</a></blockquote></div></div>
	            	</div>
	            	Mimity Online Shop<br>
					Street address<br>
					Store Town<br>
					ZIP
                                        
                   
				</div>
				<!-- End OUR LOCATION -->

        	</div>

        	<div class="clearfix visible-sm"></div>

			<!-- Cart -->
        	<div class="col-lg-9 col-md-9 col-sm-12">
        		<div class="col-lg-12 col-sm-12">
            		<span class="title">CONTACT US</span>
            	</div>
	            <div class="col-lg-12 col-sm-12 hero-feature">
					<p>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    <table class="table table-bordered tbl-checkout">
                        <tbody>
                            <tr>
                                <td>First Name</td>
                                <td>
                                    <input type="text" name="" class="form-control">
                                </td>
                            </tr>
                            <tr>
                                <td>Last Name</td>
                                <td>
                                    <input type="text" name="" class="form-control">
                                </td>
                            </tr>
                            <tr>
                                <td>Email</td>
                                <td>
                                    <input type="text" name="" class="form-control">
                                </td>
                            </tr>
                            <tr>
                                <td>Telephone</td>
                                <td>
                                    <input type="text" name="" class="form-control">
                                </td>
                            </tr>
                            <tr>
                                <td>Message</td>
                                <td colspan="3">
                                    <textarea name="" class="form-control" rows="5"></textarea>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="btn-group btns-cart">
                        <button type="button" class="btn btn-primary">Send</button>
                    </div>
	            </div>
                    
        	</div>
        	<!-- End Cart -->


        </div>
	</div>