<div class="container main-container">
        <div class="row">

        	<!-- Slider -->
        	<div class="col-lg-9 col-md-12">
                <div class="slider">
                    <div class="bx-wrapper" style="max-width: 100%; margin: 0px auto;"><div class="bx-viewport" style="width: 100%; overflow: hidden; position: relative; height: 352px;"><ul class="bxslider" style="width: 515%; position: relative; -webkit-transition-duration: 0s; transition-duration: 0s; -webkit-transform: translate3d(-2554px, 0px, 0px);"><li style="float: left; list-style: none; position: relative; width: 838px;" class="bx-clone">
                            <a href="index.html">
                                <img src="<?php echo $this->baseUrl("assets/images/banner_slider-1.jpg"); ?>" alt="">
                            </a>
                        </li>
                        <li style="float: left; list-style: none; position: relative; width: 838px;">
                            <a href="index.html">
                                <img src="<?php echo $this->baseUrl("assets/images/banner_slider-3.jpg"); ?>" alt="">
                            </a>
                        </li>
                        <li style="float: left; list-style: none; position: relative; width: 838px;">
                            <a href="index.html">
                                <img src="<?php echo $this->baseUrl("assets/images/banner_slider-2.jpg"); ?>" alt="">
                            </a>
                        </li>
                        <li style="float: left; list-style: none; position: relative; width: 838px;">
                            <a href="index.html">
                                <img src="<?php echo $this->baseUrl("assets/images/banner_slider-1.jpg"); ?>" alt="">
                            </a>
                        </li>
                    <li style="float: left; list-style: none; position: relative; width: 838px;" class="bx-clone">
                            <a href="index.html">
                                <img src="<?php echo $this->baseUrl("assets/images/banner_slider-3.jpg"); ?>" alt="">
                            </a>
                        </li></ul></div></div>
                </div>
            </div>
            <!-- End Slider -->

			<!-- Product Selection, visible only on large desktop -->
            
                        
                        
                        <div class="col-lg-3 col-md-3 col-sm-6">
<div class="thumbnail col-lg-12 col-md-12 col-sm-6 visible-lg visible-md text-center">
		                	<a href="<?php echo $this->baseUrl("/produto/index?id=1"); ?>" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="<?php echo $this->baseUrl("/assets/images/cam1frente.jpg"); ?>" alt="" style="position: absolute; width: 224px; height: auto; max-width: none; max-height: none; left: 0px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
                                        <h4><a href="<?php echo $this->baseUrl("/produto/index?id=1"); ?>">Camiseta Born To Fight</a></h4>
		                        <p>Fachada da sede Andre Gomes Team. Os melhores lutadores da historia do Muaythai tiraram fotos.</p>
		                        <p>
		                        	</p><div class="btn-group">
                                                    <center><a href="javascript:void(0)" class="btn btn-default">R$ 69,90</a></center>
                                                        <!-- INICIO FORMULARIO BOTAO PAGSEGURO -->
<form action="https://pagseguro.uol.com.br/checkout/v2/cart.html?action=add" method="post">
<!-- NÃO EDITE OS COMANDOS DAS LINHAS ABAIXO -->
<input type="hidden" name="itemCode" value="F4EDF0E5C3C33A20047A3F80163195A8" />
<input type="image" src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/pagamentos/209x48-comprar-assina.gif" name="submit" alt="Pague com PagSeguro - é rápido, grátis e seguro!" />
</form>
<!-- FINAL FORMULARIO BOTAO PAGSEGURO -->
<!--			                        	<a href="<?php echo $this->baseUrl("/produto/index?id=1"); ?>" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Comprar</a>-->
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
            </div>
            <!-- End Product Selection -->
        </div>
    
    <div class="row">
    
<div class="col-lg-3 col-md-3 col-sm-6">
					<div class="no-padding">
	            		<span class="title">NOVO PRODUTO</span>
	            	</div>
					<div class="hero-feature">
		                <div class="thumbnail text-center">
		                	<a href="<?php echo $this->baseUrl("/produto/index?id=2"); ?>" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="<?php echo $this->baseUrl("/assets/images/shortThai1.jpg"); ?>" alt="" style="position: absolute; width: 250px; height: auto; max-width: none; max-height: none; left: -13px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
		                        <h4><a href="<?php echo $this->baseUrl("/produto/index?id=2"); ?>">Short Muaythai</a></h4>
		                        <p>Short de Muaythai importado de Tailandia</p>
		                        <p>
		                        	</p><div class="btn-group">
                                                    <center><a href="#" class="btn btn-default">$ 119.00</a></center>
			                        	<!-- INICIO FORMULARIO BOTAO PAGSEGURO -->
<form action="https://pagseguro.uol.com.br/checkout/v2/cart.html?action=add" method="post">
<!-- NÃO EDITE OS COMANDOS DAS LINHAS ABAIXO -->
<input type="hidden" name="itemCode" value="B96420E3F1F19D0FF42BAFB12239A49D" />
<input type="image" src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/pagamentos/209x48-comprar-assina.gif" name="submit" alt="Pague com PagSeguro - é rápido, grátis e seguro!" />
</form>
<!-- FINAL FORMULARIO BOTAO PAGSEGURO -->
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
                                        </div>
</div>
    
    <div class="col-lg-3 col-md-3 col-sm-6">
					<div class="no-padding">
	            		<span class="title">NOVO PRODUTO</span>
	            	</div>
					<div class="hero-feature">
		                <div class="thumbnail text-center">
		                		<a href="<?php echo $this->baseUrl("/produto/index?id=1"); ?>" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="<?php echo $this->baseUrl("/assets/images/cam1frente.jpg"); ?>" alt="" style="position: absolute; width: 224px; height: auto; max-width: none; max-height: none; left: 0px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
                                        <h4><a href="<?php echo $this->baseUrl("/produto/index?id=1"); ?>">Camiseta Born To Fight</a></h4>
		                        <p>Fachada da sede Andre Gomes Team. Centro de Treinamento 1.</p>
		                        <p>
		                        	</p><div class="btn-group">
                                                    <center><a href="javascript:void(0)" class="btn btn-default">R$ 69,90</a></center>
                                                        <!-- INICIO FORMULARIO BOTAO PAGSEGURO -->
<form action="https://pagseguro.uol.com.br/checkout/v2/cart.html?action=add" method="post">
<!-- NÃO EDITE OS COMANDOS DAS LINHAS ABAIXO -->
<input type="hidden" name="itemCode" value="F4EDF0E5C3C33A20047A3F80163195A8" />
<input type="image" src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/pagamentos/209x48-comprar-assina.gif" name="submit" alt="Pague com PagSeguro - é rápido, grátis e seguro!" />
</form>
<!-- FINAL FORMULARIO BOTAO PAGSEGURO -->
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
                                        </div>
</div>
    
    
    <div class="col-lg-3 col-md-3 col-sm-6">
					<div class="no-padding">
	            		<span class="title">NOVO PRODUTO</span>
	            	</div>
					<div class="hero-feature">
		                <div class="thumbnail text-center">
		                		<a href="<?php echo $this->baseUrl("/produto/index?id=3"); ?>" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="<?php echo $this->baseUrl("/assets/images/cam3frente.jpg"); ?>" alt="" style="position: absolute; width: 224px; height: auto; max-width: none; max-height: none; left: 0px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
                                        <h4><a href="<?php echo $this->baseUrl("/produto/index?id=3"); ?>">Regata de treino</a></h4>
		                        <p>Regata de treinamento do equipe Andre Gomes.</p>
		                        <p>
		                        	</p><div class="btn-group">
                                                    <center><a href="javascript:void(0)" class="btn btn-default">R$ 60,00</a></center>
                                                    <!-- INICIO FORMULARIO BOTAO PAGSEGURO -->
<form action="https://pagseguro.uol.com.br/checkout/v2/cart.html?action=add" method="post">
<!-- NÃO EDITE OS COMANDOS DAS LINHAS ABAIXO -->
<input type="hidden" name="itemCode" value="3E629F7F7B7B827EE4BD6F889BE640BD" />
<input type="image" src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/pagamentos/209x48-comprar-assina.gif" name="submit" alt="Pague com PagSeguro - é rápido, grátis e seguro!" />
</form>
<!-- FINAL FORMULARIO BOTAO PAGSEGURO -->
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
                                        </div>
</div>
    
        <div class="col-lg-3 col-md-3 col-sm-6">
					<div class="no-padding">
	            		<span class="title">NOVO PRODUTO</span>
	            	</div>
					<div class="hero-feature">
		                <div class="thumbnail text-center">
		                		<a href="<?php echo $this->baseUrl("/produto/index?id=4"); ?>" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="<?php echo $this->baseUrl("/assets/images/cam4frente.jpg"); ?>" alt="" style="position: absolute; width: 224px; height: auto; max-width: none; max-height: none; left: 0px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
                                        <h4><a href="<?php echo $this->baseUrl("/produto/index?id=4"); ?>">Regata de treinamento</a></h4>
		                        <p>Regata de treinamento preta com logo da equipe Andre Gomes.</p>
		                        <p>
		                        	</p><div class="btn-group">
                                                    <center><a href="javascript:void(0)" class="btn btn-default">R$ 60,00</a></center>
                                                    <!-- INICIO FORMULARIO BOTAO PAGSEGURO -->
<form action="https://pagseguro.uol.com.br/checkout/v2/cart.html?action=add" method="post">
<!-- NÃO EDITE OS COMANDOS DAS LINHAS ABAIXO -->
<input type="hidden" name="itemCode" value="3E629F7F7B7B827EE4BD6F889BE640BD" />
<input type="image" src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/pagamentos/209x48-comprar-assina.gif" name="submit" alt="Pague com PagSeguro - é rápido, grátis e seguro!" />
</form>
<!-- FINAL FORMULARIO BOTAO PAGSEGURO -->
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
                                        </div>
</div>
        </div>
    


    
    <div class="row">
    
<div class="col-lg-3 col-md-3 col-sm-6">
					<div class="no-padding">
	            		<span class="title">NOVO PRODUTO</span>
	            	</div>
					<div class="hero-feature">
		                <div class="thumbnail text-center">
		                	<a href="<?php echo $this->baseUrl("/produto/index?id=5"); ?>" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="<?php echo $this->baseUrl("/assets/images/cam5frente.jpg"); ?>" alt="" style="position: absolute; width: 250px; height: auto; max-width: none; max-height: none; left: -13px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
		                        <h4><a href="<?php echo $this->baseUrl("/produto/index?id=5"); ?>">Regata de treinamento</a></h4>
		                        <p>Regata de treinamento preta com logo da equipe Andre Gomes.</p>
		                        <p>
		                        	</p><div class="btn-group">
                                                    <center><a href="#" class="btn btn-default">$ 60.00</a></center>
			                        	<!-- INICIO FORMULARIO BOTAO PAGSEGURO -->
<form action="https://pagseguro.uol.com.br/checkout/v2/cart.html?action=add" method="post">
<!-- NÃO EDITE OS COMANDOS DAS LINHAS ABAIXO -->
<input type="hidden" name="itemCode" value="B96420E3F1F19D0FF42BAFB12239A49D" />
<input type="image" src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/pagamentos/209x48-comprar-assina.gif" name="submit" alt="Pague com PagSeguro - é rápido, grátis e seguro!" />
</form>
<!-- FINAL FORMULARIO BOTAO PAGSEGURO -->
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
                                        </div>
</div>
    
        </div>
    
    
    
    
    
    
    
    
     <!--  <div class="row">
        	<div class="col-lg-3 col-md-3 col-sm-12">

        	
        		<div class="col-lg-12 col-md-12 col-sm-6">
	        		<div class="no-padding">
	            		<span class="title">CATEGORIES</span>
	            	</div>

					<div id="main_menu">
                        <div class="list-group panel panel-cat">
                            <a href="#sub1" class="list-group-item" data-toggle="collapse" data-parent="#main_menu">Cras justo odio <i class="fa fa-caret-down pull-right"></i></a>
                            <div class="collapse list-group-sub" id="sub1">
                                <a href="#SubMenu1" class="list-group-item" data-toggle="collapse" data-parent="#SubMenu1">Subitem 1 <i class="fa fa-caret-down"></i></a>
                                <div class="collapse list-group-submenu" id="SubMenu1">
                                    <a href="#" class="list-group-item" data-parent="#SubMenu1">Subitem 1 a</a>
                                    <a href="#" class="list-group-item" data-parent="#SubMenu1">Subitem 2 b</a>
                                    <a href="#SubSubMenu1" class="list-group-item" data-toggle="collapse" data-parent="#SubSubMenu1">Subitem 3 c <i class="fa fa-caret-down"></i></a>
                                    <div class="collapse list-group-submenu list-group-submenu-1" id="SubSubMenu1">
                                        <a href="#" class="list-group-item" data-parent="#SubSubMenu1">Sub sub item 1</a>
                                        <a href="#" class="list-group-item" data-parent="#SubSubMenu1">Sub sub item 2</a>
                                    </div>
                                    <a href="#" class="list-group-item" data-parent="#SubMenu1">Subitem 4 d</a>
                                </div>
                                <a href="javascript:;" class="list-group-item">Subitem 2</a>
                                <a href="javascript:;" class="list-group-item">Subitem 3</a>
                            </div>
                            <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
                            <a href="#sub2" class="list-group-item" data-toggle="collapse" data-parent="#main_menu">Porta ac consectetur ac <i class="fa fa-caret-down pull-right"></i></a>
                            <div class="collapse list-group-sub" id="sub2">
                                <a href="" class="list-group-item">Subitem 1</a>
                                <a href="" class="list-group-item">Subitem 2</a>
                                <a href="" class="list-group-item">Subitem 3</a>
                            </div>
                            <a href="#" class="list-group-item">Vestibulum at eros</a>
                            <a href="#" class="list-group-item">Porta ac consectetur ac</a>
                            <a href="#" class="list-group-item">Cras justo odio</a>
                            <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
                            <a href="#" class="list-group-item">Porta ac consectetur ac</a>
                            <a href="#" class="list-group-item">Vestibulum at eros</a>
                            <a href="#" class="list-group-item">Porta ac consectetur ac</a>
                        </div>
                    </div>

				</div> 
				
				<div class="col-lg-12 col-md-12 col-sm-6">
					<div class="no-padding">
	            		<span class="title">BEST SELLER</span>
	            	</div>
					<div class="hero-feature">
		                <div class="thumbnail text-center">
		                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="<?php echo $this->baseUrl("assets/images/product-8.jpg"); ?>" alt="" style="position: absolute; width: 250px; height: auto; max-width: none; max-height: none; left: -13px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
		                        <h4><a href="detail.html">Penn State College T-Shirt</a></h4>
		                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
		                        <p>
		                        	</p><div class="btn-group">
			                        	<a href="#" class="btn btn-default">$ 528.96</a>
			                        	<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
		            </div>
		            <div class="hero-feature hidden-sm">
		                <div class="thumbnail text-center">
		                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="<?php echo $this->baseUrl("assets/images/product-9.jpg"); ?>" alt="" style="position: absolute; width: 280px; height: auto; max-width: none; max-height: none; left: -28px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
		                        <h4><a href="detail.html">Ohio State College T-Shirt</a></h4>
		                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
		                        <p>
		                        	</p><div class="btn-group">
			                        	<a href="#" class="btn btn-default">$ 924.25</a>
			                        	<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
		            </div>
				</div> 
				

        	</div>

        	<div class="clearfix visible-sm"></div>

		
        	<div class="col-lg-9 col-md-9 col-sm-12">
        		<div class="col-lg-12 col-sm-12">
            		<span class="title">FEATURED PRODUCTS</span>
            	</div>
	            <div class="col-lg-4 col-sm-4 hero-feature text-center">
	                <div class="thumbnail">
	                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
	                    	<img src="<?php echo $this->baseUrl("assets/images/product-2.jpg"); ?>" alt="" style="position: absolute; width: 250px; height: auto; max-width: none; max-height: none; left: -4px; top: 0px;">
	                	</a>
	                    <div class="caption prod-caption">
	                        <h4><a href="detail.html">Age Of Wisdom Tan Graphic Tee</a></h4>
	                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
	                        <p>
	                        	</p><div class="btn-group">
		                        	<a href="#" class="btn btn-default">$ 122.51</a>
		                        	<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
	                        	</div>
	                        <p></p>
	                    </div>
	                </div>
	            </div>
	            <div class="col-lg-4 col-sm-4 hero-feature text-center">
	                <div class="thumbnail">
	                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
	                    	<img src="<?php echo $this->baseUrl("assets/images/product-3.jpg"); ?>" alt="" style="position: absolute; width: 250px; height: auto; max-width: none; max-height: none; left: -4px; top: 0px;">
	                	</a>
	                    <div class="caption prod-caption">
	                        <h4><a href="detail.html">Classic Laundry Green Graphic T-Shirt</a></h4>
	                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
	                        <p>
	                        	</p><div class="btn-group">
		                        	<a href="#" class="btn btn-default">$ 628.96</a>
		                        	<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
	                        	</div>
	                        <p></p>
	                    </div>
	                </div>
	            </div>
	            <div class="col-lg-4 col-sm-4 hero-feature text-center">
	                <div class="thumbnail">
	                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
	                    	<img src="<?php echo $this->baseUrl("assets/images/product-4.jpg"); ?>" alt="" style="position: absolute; width: 250px; height: auto; max-width: none; max-height: none; left: -4px; top: 0px;">
	                	</a>
	                    <div class="caption prod-caption">
	                        <h4><a href="detail.html">Disc Jockey Print T-Shirt</a></h4>
	                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
	                        <p>
	                        	</p><div class="btn-group">
		                        	<a href="#" class="btn btn-default">$ 394.64</a>
		                        	<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
	                        	</div>
	                        <p></p>
	                    </div>
	                </div>
	            </div>
	            <div class="col-lg-4 col-sm-4 hero-feature text-center">
	                <div class="thumbnail">
	                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
	                    	<img src="<?php echo $this->baseUrl("assets/images/product-5.jpg"); ?>" alt="" style="position: absolute; width: 250px; height: auto; max-width: none; max-height: none; left: -4px; top: 0px;">
	                	</a>
	                    <div class="caption prod-caption">
	                        <h4><a href="detail.html">Live Nation 3 Days of Peace and Music Carbon</a></h4>
	                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
	                        <p>
	                        	</p><div class="btn-group">
	                        		<a href="#" class="btn btn-default">$ 428.96</a>
	                        		<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
	                        	</div>
	                        <p></p>
	                    </div>
	                </div>
	            </div>
	            <div class="col-lg-4 col-sm-4 hero-feature text-center">
	                <div class="thumbnail">
	                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
	                    	<img src="<?php echo $this->baseUrl("assets/images/product-6.jpg"); ?>" alt="" style="position: absolute; width: 250px; height: auto; max-width: none; max-height: none; left: -4px; top: 0px;">
	                	</a>
	                    <div class="caption prod-caption">
	                        <h4><a href="detail.html">Live Nation ACDC Gray T-Shirt</a></h4>
	                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
	                        <p>
	                        	</p><div class="btn-group">
	                        		<a href="#" class="btn btn-default">$ 428.96</a>
	                        		<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
	                        	</div>
	                        <p></p>
	                    </div>
	                </div>
	            </div>
	            <div class="col-lg-4 col-sm-4 hero-feature text-center">
	                <div class="thumbnail">
	                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
	                    	<img src="<?php echo $this->baseUrl("assets/images/product-7.jpg"); ?>" alt="" style="position: absolute; width: 250px; height: auto; max-width: none; max-height: none; left: -4px; top: 0px;">
	                	</a>
	                    <div class="caption prod-caption">
	                        <h4><a href="detail.html">Live Nation Aerosmith Ivory T-Shirt</a></h4>
	                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
	                        <p>
	                        	</p><div class="btn-group">
	                        		<a href="#" class="btn btn-default">$ 632.15</a>
	                        		<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
	                        	</div>
	                        <p></p>
	                    </div>
	                </div>
	            </div>
        	</div>
        	

        	<div class="clearfix visible-sm"></div>

			
        	<div class="col-lg-9 col-md-9 col-sm-12">
				<div class="col-lg-12 col-sm-12">
            		<span class="title">ADIDAS</span>
            	</div>
	            <div class="col-lg-4 col-sm-4 hero-feature text-center">
	                <div class="thumbnail">
	                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
	                    	<img src="<?php echo $this->baseUrl("assets/images/product-10.jpg"); ?>" alt="" style="position: absolute; width: 242px; height: 258px; max-width: none; max-height: none; left: 0px; top: 0px;">
	                	</a>
	                    <div class="caption prod-caption">
	                        <h4><a href="detail.html">Adidas Men Blue &amp; Red Striped Polo T-shirt </a></h4>
	                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
	                        <p>
	                        	</p><div class="btn-group">
		                        	<a href="#" class="btn btn-default">$ 22.22</a>
		                        	<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
	                        	</div>
	                        <p></p>
	                    </div>
	                </div>
	            </div>
	            <div class="col-lg-4 col-sm-4 hero-feature text-center">
	                <div class="thumbnail">
	                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
	                    	<img src="<?php echo $this->baseUrl("assets/images/product-11.jpg"); ?>" alt="" style="position: absolute; width: 248px; height: auto; max-width: none; max-height: none; left: -3px; top: 0px;">
	                	</a>
	                    <div class="caption prod-caption">
	                        <h4><a href="detail.html">Adidas Men Flame Black T-shirt</a></h4>
	                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
	                        <p>
	                        	</p><div class="btn-group">
	                        		<a href="#" class="btn btn-default">$ 15.47</a>
	                        		<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
	                        	</div>
	                        <p></p>
	                    </div>
	                </div>
	            </div>
	            <div class="col-lg-4 col-sm-4 hero-feature text-center">
	                <div class="thumbnail">
	                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
	                    	<img src="<?php echo $this->baseUrl("assets/images/product-12.jpg"); ?>" alt="" style="position: absolute; width: 251px; height: auto; max-width: none; max-height: none; left: -4px; top: 0px;">
	                	</a>
	                    <div class="caption prod-caption">
	                        <h4><a href="detail.html">Adidas Men Red Printed T-shirt</a></h4>
	                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, minima!</p>
	                        <p>
	                        	</p><div class="btn-group">
	                        		<a href="#" class="btn btn-default">$ 20.63</a>
	                        		<a href="#" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Buy</a>
	                        	</div>
	                        <p></p>
	                    </div>
	                </div>
	            </div>
			</div>
		

        </div> -->
	</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-65111921-1', 'auto');
  ga('send', 'pageview');

</script>

