<div class="container main-container">
        <div class="row">
        	<div class="col-lg-3 col-md-3 col-sm-6">
					<div class="no-padding">
	            		<span class="title">NOVO PRODUTO</span>
	            	</div>
					<div class="hero-feature">
		                <div class="thumbnail text-center">
		                	<a href="<?php echo $this->baseUrl("/produto/index?id=2"); ?>" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="<?php echo $this->baseUrl("/assets/images/shortThai1.jpg"); ?>" alt="" style="position: absolute; width: 250px; height: auto; max-width: none; max-height: none; left: -13px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
		                        <h4><a href="<?php echo $this->baseUrl("/produto/index?id=2"); ?>">Short Muaythai</a></h4>
		                        <p>Short de Muaythai importado de Tailandia</p>
		                        <p>
		                        	</p><div class="btn-group">
                                                    <center><a href="#" class="btn btn-default">$ 119.00</a></center>
			                        	<!-- INICIO FORMULARIO BOTAO PAGSEGURO -->
<form action="https://pagseguro.uol.com.br/checkout/v2/cart.html?action=add" method="post">
<!-- NÃO EDITE OS COMANDOS DAS LINHAS ABAIXO -->
<input type="hidden" name="itemCode" value="B96420E3F1F19D0FF42BAFB12239A49D" />
<input type="image" src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/pagamentos/209x48-comprar-assina.gif" name="submit" alt="Pague com PagSeguro - é rápido, grátis e seguro!" />
</form>
<!-- FINAL FORMULARIO BOTAO PAGSEGURO -->
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
                                        </div>
</div>
        	<div class="clearfix visible-sm"></div>

			<!-- Cart -->
        	<div class="col-lg-9 col-md-9 col-sm-12">
        		<div class="col-lg-12 col-sm-12">
            		<span class="title">SOBRE NOS</span>
            	</div>
                    <div class="col-lg-12 col-sm-12 hero-feature">
                        <iframe width="420" height="315" src="https://www.youtube.com/embed/Bh1jtVImnXE" frameborder="0" allowfullscreen></iframe>
                    </div>
                    <div class="col-lg-12 col-sm-12 hero-feature">
                        <iframe width="420" height="315" src="https://www.youtube.com/embed/M98V5aY5OJw" frameborder="0" allowfullscreen></iframe>
                    </div>
        	</div>
        	<!-- End Cart -->


        </div>
	</div>