<div class="container main-container">
        <div class="row">
        	<div class="col-lg-3 col-md-3 col-sm-12">

				<!-- RECENT PRODUCT -->
				<div class="col-lg-12 col-md-12 col-sm-12 visible-lg visible-md">
					<div class="no-padding">
	            		<span class="title">RECENTES</span>
	            	</div>
		                <div class="thumbnail col-lg-12 col-md-12 col-sm-6 visible-lg visible-md text-center">
		                	<a href="detail.html" class="link-p" style="overflow: hidden; position: relative;">
		                    	<img src="<?php echo $this->baseUrl("assets/images/cam1frente.jpg"); ?>" alt="" style="position: absolute; width: 289px; height: auto; max-width: none; max-height: none; left: -33px; top: 0px;">
		                	</a>
		                    <div class="caption prod-caption">
		                        <h4><a href="detail.html">Camiseta Born To Fight</a></h4>
		                        <p>Fachada da sede do Andre Gomes Team. Os melhores lutadores da historia do Muaythai tiraram fotos.</p>
		                        <p>
		                        	</p><div class="btn-group">
                                                    <center><a href="#" class="btn btn-default">R$ 69,90</a></center>
			                        	<form action="https://pagseguro.uol.com.br/checkout/v2/cart.html?action=add" method="post">
<!-- N?O EDITE OS COMANDOS DAS LINHAS ABAIXO -->
<input type="hidden" name="itemCode" value="F4EDF0E5C3C33A20047A3F80163195A8">
<input type="image" src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/pagamentos/209x48-comprar-assina.gif" name="submit" alt="Pague com PagSeguro - ? r?pido, gr?tis e seguro!">
</form>
		                        	</div>
		                        <p></p>
		                    </div>
		                </div>
                                    

                                    
				</div>
				<!-- End RECENT PRODUCT -->

        	</div>

        	<div class="clearfix visible-sm"></div>

			<!-- Cart -->
        	<div class="col-lg-9 col-md-9 col-sm-12">
        		<div class="col-lg-12 col-sm-12">
            		<span class="title">PRENSA</span>
            	</div>
	            <div class="col-lg-12 col-sm-12 hero-feature">
                        <h4><a href="http://www.grandesmestresmarciais.com.br/?p=mestres&cat=1&id=29" TARGET="_BLANK">Grandes Mestres</a></h4>

                        <h4><a href="https://www.youtube.com/watch?v=29ORauAWqaw" TARGET="_BLANK">Entrevista Canal Combate</a></h4>
		
                        <h4><a href="http://www.oregional.com.br/2014/07/mestre-de-muay-thai-visita-catanduva-e-realiza-prova-de-graduacao_310990">O Regional</a></h4>
                        
                        <h4><a href="http://www.amazonianarede.com.br/federacao-de-muay-thai-qualifica-treinadores-e-atletas-em-seminario/" TARGET="_BLANK">Amazonia Na Rede</a></h4>
                    
                        <h4><a href="http://newscombat2010.xpg.uol.com.br/crbst_1.html" TARGET="_BLANK">News Combat</a></h4>
                   
                        <h4><a href="http://www.maxfight.com.br/site/noticias/15-o-maior-confronto-entre-equipes-da-regiao.html" TARGET="_BLANK">Max Fight</a></h4>    
                    </div>
        	</div>
        	<!-- End Cart -->


        </div>
	</div>