CREATE TABLE `produtos` (
  `ID_ID_PROD` INT NOT NULL AUTO_INCREMENT,
  `ST_NOME_PROD` VARCHAR(100) NOT NULL,
  `ST_MINIDESC_PROD` VARCHAR(255) NULL,
  `ST_DESCRICAO_PROD` TEXT NULL,
  `ST_DETALHES_PROD` TEXT NULL,
  `VL_PRECO_PROD` DECIMAL(2) NOT NULL,
  `NM_STOCK_PROD` INT NULL DEFAULT 0,
  PRIMARY KEY (`ID_ID_PROD`));

CREATE TABLE `usuarios` (
  `ID_ID_USU` INT NOT NULL AUTO_INCREMENT,
  `ST_EMAIL_USU` VARCHAR(100) NOT NULL,
  `ST_SENHA_USU` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_ID_USU`));

ALTER TABLE `produtos` 
CHANGE COLUMN `ST_DETALHES_PROD` `ST_HISTORIA_PROD` TEXT NULL DEFAULT NULL ;

